# Generated by Django 6.0.3 on 2026-04-05 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название игры')),
                ('developer', models.CharField(blank=True, max_length=100, verbose_name='Разработчик')),
                ('engine', models.CharField(choices=[('Unity', 'Unity'), ('Unreal Engine', 'Unreal Engine'), ('Godot', 'Godot'), ('Custom', 'Другой/Кастомный')], max_length=20, verbose_name='Движок')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выхода')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Оценка')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('save_progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс прохождения %')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='games/logos/', verbose_name='Логотип/Обложка')),
            ],
            options={
                'verbose_name': 'Игра в коллекции',
                'verbose_name_plural': 'Игры в коллекции',
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Character3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('role', models.CharField(choices=[('protagonist', 'Главный герой'), ('companion', 'Напарник'), ('enemy', 'Противник'), ('boss', 'Босс'), ('npc', 'NPC')], max_length=20, verbose_name='Роль')),
                ('polygon_count', models.PositiveIntegerField(verbose_name='Количество полигонов')),
                ('has_rig', models.BooleanField(default=False, verbose_name='Есть риг (скелет)')),
                ('texture_resolution', models.CharField(choices=[('1K', '1024x1024'), ('2K', '2048x2048'), ('4K', '4096x4096'), ('8K', '8192x8192')], max_length=10, verbose_name='Разрешение текстур')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания/добавления')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='characters/thumbnails/', verbose_name='Превью модели')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.librarygame', verbose_name='Игра')),
            ],
            options={
                'verbose_name': '3D-персонаж',
                'verbose_name_plural': '3D-персонажи',
                'ordering': ['-created_date', 'name'],
            },
        ),
    ]
