# Generated by Django 6.0.3 on 2026-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character3d',
            name='has_rig',
        ),
        migrations.RemoveField(
            model_name='character3d',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='character3d',
            name='polygon_count',
        ),
        migrations.RemoveField(
            model_name='character3d',
            name='role',
        ),
        migrations.RemoveField(
            model_name='character3d',
            name='texture_resolution',
        ),
        migrations.AddField(
            model_name='character3d',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='character3d',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='characters/models/', verbose_name='3D модель'),
        ),
    ]
